### ISSUE TITLE
Use Of Loader for background Task

### ISSUE THREAD

**Issue by yashLadha** [RajuKoushik/Travel_Diaries_App#9]
In the code we have used AsyncTask for background Network related Task . Whenever the user clicks or rotate the screen it gets created again which is a costly operation. Instead of using the AsyncTask we can use the loader for the same Task.

**Comment by RajuKoushik** [comment]
True !! The Loader class does a better job of updating the Cursor information whenever the underlying data changes and yeah it can handle the activity changes with much more ease. So using the [AsyncTaskLoader](https://developer.android.com/reference/android/content/AsyncTaskLoader.html) would be a better option. Cheers.

**Comment by yashLadha** [comment]
Is using AsyncTask would be beneficial?

**Comment by RajuKoushik** [comment]
Nope the Loader class would be much better. AsyncTask**Loader** is different from the AsyncTask. The AsyncTaskLoader extends the Loader class itself and is different from the AsyncTask.

**Comment by yashLadha** [comment]
Okk then i will make the necessary changes

**Comment by RajuKoushik** [comment]
Sure :) You must have got the difference.  Cheers.

**Comment by yashLadha** [comment]
Closes from PR #11
